### ISSUE TITLE
It can't be compile with a pythoneval.txt .

### ISSUE THREAD

**Issue by boonthum082** [KwiatQIM/Quantum-Tomography#1]
invalid syntax (pythoneval.txt, line 1)<br>Traceback (most recent call last):<br>  File 'RunScript.py', line 6, in <module><br>    exec(open('State_Tomography_WebsiteLib.py').read())<br>  File '<string>', line 32, in <module><br>  File 'Quantum-Tomography_Git/QuantumTomography/TomoClass.py', line 144, in importEval<br>    exec(compile(open(evaltxt, 'rb').read(), evaltxt, 'exec'))<br>  File 'pythoneval.txt', line 1<br>    tomo_input = np.array([[1,0,,1,0],[1,0,,0,1],[1,0,,0.7071,0.7071],[1,0,,0.7071,-0.7071],[1,0,,0.7071,0.7071j],[1,0,,0.7071,-0.7071j]])<br>

**Comment by smturro2** [comment]
Hey thanks for reporting the issue. It looks like there was a problem with getting the input for the coincidences. Can you confirm that you inputted values into the coincidences column before clicking run?

**Comment by smturro2** [comment]
We've added a new feature that handles invalid inputs in our website. This should cover errors of this type.
