### ISSUE TITLE
MLE tomography is exceeding max func evals in scipy.optimize.leastsq

### ISSUE THREAD

**Issue by dannypaulson** [KwiatQIM/Quantum-Tomography#29]
Hi there, 

I'm a new user of your package and wanted to ask a question about an issue I've encountered. For some relatively simple tomography examples on 1 or 2 qubits, I am getting warnings from `scipy.optimize.leastsq` that the maximum number of function evaluations has been exceeded, meaning the optimization exited before it converged. The `leastsq` function has a parameter `maxfeval` that can be used to set the number of allowed evaluations to some higher number to let the optimization converge, but this parameter is not exposed in the `StateTomography` method of the `Tomography` class or anywhere else that I can see. Do you see a fix for this?

Thanks for your help!

Danny

**Comment by smturro2** [comment]
Hi Danny,

Thanks for reaching out. I think this is a wonderful idea. We currently do
not have anyone maintaining the code to implement this feature. I’m going
to see if I still have permissions to implement the request. Progress may
be slow but I’ll keep you posted.

Thanks,
Scott Turro

**Comment by smturro2** [comment]
@dannypaulson A new version has been published. version 1.05.0 will allow you to pass the parameters in through the config

**Comment by dannypaulson** [comment]
Thanks so much!
